# Generated by Django 3.2.16 on 2025-08-16 09:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import subscriptions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_type', models.CharField(choices=[('full', 'Full'), ('discount', 'Discount')], default='full', max_length=20)),
                ('discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_type', models.CharField(choices=[('human', 'Human'), ('mountain', 'Mountain'), ('sky', 'Sky')], max_length=128)),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tariff', models.ForeignKey(default=subscriptions.models.get_default_tariff, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.tariff')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
